spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: subscriptionRoute
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/subscription/**
        - id: courseRoute
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/course/**
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

