spring:
  application:
    name: movie
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev

rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 5672

queue:
  movie:
    name: MovieQueue

message: Ok

resilience4j:
  circuitbreaker:
    instances:
      movie:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failueRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCalssInHalfOpenState: 3
        automaticTransitionFromOpenToHalfIfOpenEnabled: true


  retry:
    instances:
      movie:
        maxAttempts: 3
        waitDuration: 1000

        retryExceptions:
          - feign.FeignException$InternalServerError
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
