spring:
  application:
    name: api-conta
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port:5672

Queue:
  api-usuario:
    name: UsuarioQueue

#configuração circuit breaker
resilience4j:
  circuitbreaker:
    instances:
      api-usuario:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failueRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCalssInHalfOpenState: 3
        automaticTransitionFromOpenToHalfIfOpenEnabled: true

#Configuração do mecanismo de novas tentativas
  retry:
    instances:
      api-usuario:
        maxAttempts: 3
        waitDuration: 1000
        #retryExceptions[0]: feign.FeignExceptions$InternalServerError
        retryExceptions:
          - feign.FeignException$InternalServerError
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException

#Configuração Actuator
management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info
  health:
      circuitbreakers:
          enabled: true
  endpoint:
    health:
      show-details: always
