spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev
    gateway:
      default-filters:
        - TokenRelay
  security:
    oauth2:
      client:
        #        provider:
        #          google:
        #            issuer-uri: https://account.google.com
        registration:
          google:
            client-id: 406906485125-1plnfuuomv8cgedee080j4apfv4e4bot.apps.googleusercontent.com
            client-secret: ${nomeVariavel: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}
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/google