version: '3.2'

services:
  zipkin-service:
    image: openzipkin/zipkin:2
    container_name: zipkin-service
    ports:
      - 9411:9411

  eureka-service:
    build: eureka-service
    container_name: eureka-service
    depends_on:
      - zipkin-service
    ports:
      - 8761:8761

  config-server:
    build: server-config
    container_name: config-server
    depends_on:
      - eureka-service
    ports:
      - 8888:8888

  movie-service:
    build: movie-service
    container_name: movie-service
    depends_on:
      - eureka-service
    ports:
      - 8001:8001

  catalog-service:
    build: catalog-service
    container_name: catalog-service
    depends_on:
      - eureka-service
      - movie-service
    ports:
      - 8002:8002

  api-gateway:
    build: api-gateway 
    container_name: api-gateway
    depends_on:
      - eureka-service
      - movie-service
      - catalog-service
    ports:
      - 8080:8080
